### ISSUE TITLE
Linux resulting apps

### ISSUE THREAD

**Issue by egorf** [JensReimann/rtklib-qt#5]
Hi!

Great project. I was hoping to test it on Linux. But after building it with `qmake` and `make` I can only see  .exe files in bin. Where should I look for the Linux version of GUI programs?

Thanks!

**Comment by JensReimann** [comment]
under linux the resulting executables are normally located in their source directory (./app/<app_name>/ where <app_name> is something "_qt") e.g. ./app/rtkget_qt/
