### ISSUE TITLE
Any idea if this will be adopted by T.TAKASU?

### ISSUE THREAD

**Issue by astrodanco** [JensReimann/rtklib-qt#6]
Please accept my apology for opening an issue when all I have is a quick question. I was looking for a way to email you and didn't see one otherwise I would have made this an email.

Do you think T.TAKASU will eventually merge this port back into his library or has he blown you off?

I'd love to see this completed and merged. Then I could build and run the GUI apps with Visual Studio Express rather than RAD Studio.

**Comment by JensReimann** [comment]
When Tomoji Takasu started rtklib VCL and the compiler was available for free. As they changed their policy he had no time to rewrite the GUI applications. So he told me he was glad about the Qt port.

Nevertheless, I have to apply the recent changes from rtklib to this branch before asking Tomoji Takasu again for merging.

**Comment by treaves** [comment]
What's been ported to Qt?

**Comment by JensReimann** [comment]
rtkget, rtknavi, rtkplot, rtkpost, rtklaunch, rtkconv, srctblbrows and strsvr have been ported (with _qt Suffix). The lastest version is now RTKLIB repository (not here anymore) in rtk_2.4.3 branch. 

Today Takasu merged the code to his repository, too.

**Comment by treaves** [comment]
Ah, that explains why I didn't see it in this repo.  Hopefully it supports the latest Qt and the changes to the web engine.

Thanks for the response, I appreciate it.
