### ISSUE TITLE
qt version

### ISSUE THREAD

**Issue by wangleiyyy** [JensReimann/rtklib-qt#7]
for i can not complie the project, 
could you tell me the qt detail version for complie?
thank you

**Comment by JensReimann** [comment]
This repository is death. Please use JensReimann/RTKLIB.

Check out the sources and be sure to have the QT developer packages installed. Then type "qmake -recursive" and "make" to compile the sources. The final binaries are located in the corresponding application directories found under apps.

Best regards,
Jens
